name: Deploy Content to la-sentinel-playground-01 [b6f59638-6ecf-442c-9837-b74b26066eca]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-b6f59638-6ecf-442c-9837-b74b26066eca.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-b6f59638-6ecf-442c-9837-b74b26066eca.yml'

jobs:
  deploy-content:
    needs: bVSOC-build-bicep  
    bVSOC-build-bicep:
    runs-on: ubuntu-latest
    env:
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      rootDirectory: '${{ github.workspace }}'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: build bicep files using powershell 
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/bVSOC-build-bicep.ps1
    - name: check if there are any changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
    - name: commit
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
          git config user.name bicep-builder
          git config user.email bicep@builder.com
          git add -A
          git commit -m "arm files built from bicep"
          git push
    - name: sleep 5s
      run: sleep 5s
    runs-on: windows-latest
    env:
      resourceGroupName: 'rg-sentinel-playground-01'
      workspaceName: 'la-sentinel-playground-01'
      workspaceId: 'ebaf1c34-d98f-43ad-8ac1-28ebd6c696b6'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_b6f596386ecf442c9837b74b26066eca }}
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook,Watchlist,Queries'
      branch: 'main'
      sourceControlId: 'b6f59638-6ecf-442c-9837-b74b26066eca'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_b6f596386ecf442c9837b74b26066eca }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_b6f596386ecf442c9837b74b26066eca }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_b6f596386ecf442c9837b74b26066eca }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-b6f59638-6ecf-442c-9837-b74b26066eca.ps1